USE dbi549842_warehousem

CREATE TABLE [Address](
AddressId INT PRIMARY KEY IDENTITY(1,1),
Country VARCHAR(50) NOT NULL,
City VARCHAR(50) NOT NULL,
StreetName VARCHAR(50) NOT NULL,
StreetNumber INT NOT NULL,
Zip INT NOT NULL
);

CREATE TABLE Warehouse(
WarehouseId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL,
AddressId INT NOT NULL FOREIGN KEY REFERENCES [Address](AddressId)
);

SELECT * FROM Warehouse
DROP TABLE Warehouse
INSERT INTO Warehouse ([Name]) VALUES
('IvoWarehouse')

CREATE TABLE EmployeeStatus(
EmployeeStatusId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE [Role](
RoleId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE Employee(
EmployeeId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL,
[Password] VARCHAR(255) NOT NULL,
PhoneNumber VARCHAR(20) NOT NULL,
EmployeeStatusId INT NOT NULL FOREIGN KEY REFERENCES EmployeeStatus(EmployeeStatusId),
WarehouseId INT NOT NULL FOREIGN KEY REFERENCES Warehouse(WarehouseId),
RoleId INT NOT NULL FOREIGN KEY REFERENCES [Role](RoleId)
);

CREATE TABLE OrderStatus(
OrderStatusId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE [Order](
OrderId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL,
OrderDate DATETIME NOT NULL,
OrderStatusId INT NOT NULL FOREIGN KEY REFERENCES OrderStatus(OrderStatusId),
CreateById INT NOT NULL FOREIGN KEY REFERENCES Employee(EmployeeId),
AssignedToId INT FOREIGN KEY REFERENCES Employee(EmployeeId)
);

CREATE TABLE [Zone](
ZoneId INT PRIMARY KEY IDENTITY (1,1),
[Name] VARCHAR(50) NOT NULL,
Capacity DECIMAL NOT NULL,
WarehouseId INT NOT NULL FOREIGN KEY REFERENCES Warehouse(WarehouseId)
);

CREATE TABLE Inventory(
InventoryId INT PRIMARY KEY IDENTITY(1,1),
Quantity INT NOT NULL,
LastUpdate DATETIME NOT NULL,
ProductId INT NOT NULL FOREIGN KEY REFERENCES [Product](ProductId),
ZoneId INT NOT NULL FOREIGN KEY REFERENCES [Zone](ZoneId)
);

CREATE TABLE Category(
CategoryId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE [Product](
ProductId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL,
Price DECIMAL NOT NULL,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES Category(CategoryId)
);

CREATE TABLE UnitType(
UnitTypeId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE OrderProduct(
OrderProductId INT PRIMARY KEY IDENTITY(1,1),
Quantity INT NOT NULL,
TotalPrice DECIMAL NOT NULL,
OrderId INT NOT NULL FOREIGN KEY REFERENCES [Order](OrderId),
ProductId INT NOT NULL FOREIGN KEY REFERENCES [Product](ProductId),
UnitTypeId INT NOT NULL FOREIGN KEY REFERENCES UnitType(UnitTypeId)
);